"""Declarative base and shared column conventions.

Two decisions here are cheap now and expensive later, so they are made in
Milestone 1:

1. **Constraint naming convention.** Without it, Alembic autogenerate produces
   migrations that cannot reliably drop unnamed constraints, and PostgreSQL
   assigns names that differ between environments. Fixing this after a dozen
   migrations exist is genuinely painful.

2. **Timezone-aware timestamps everywhere.** Incident timelines (Milestone 10)
   and root-cause correlation (Milestone 9) compare ACOP events against
   Prometheus, syslog, and Windows event timestamps. Naive datetimes make that
   correlation quietly wrong rather than loudly broken.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func

# Aliased: SQLAlchemy exports this name uppercase, and the alias keeps it
# visually distinct from the stdlib uuid.UUID used in the annotations below.
from sqlalchemy.dialects.postgresql import UUID as PostgresUuid  # noqa: N811
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Root declarative base for all ACOP tables."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Adds a UUID primary key.

    UUIDs rather than sequential integers because assets, incidents and audit
    records will eventually be created by multiple collectors concurrently and
    referenced across systems. Generated application-side so that the value is
    known before the flush, which simplifies writing an audit record that
    references the object it describes.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PostgresUuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Adds creation and update timestamps, generated by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
