"""Declarative base and shared column conventions.

Two decisions here are cheap now and expensive later, so they are made in
Milestone 1:

1. **Constraint naming convention.** Without it, Alembic autogenerate produces
   migrations that cannot reliably drop unnamed constraints, and PostgreSQL
   assigns names that differ between environments. Fixing this after a dozen
   migrations exist is genuinely painful.

2. **Timezone-aware timestamps everywhere.** Incident timelines (Milestone 10)
   and root-cause correlation (Milestone 9) compare ACOP events against
   Prometheus, syslog, and Windows event timestamps. Naive datetimes make that
   correlation quietly wrong rather than loudly broken.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, func

# Aliased: SQLAlchemy exports this name uppercase, and the alias keeps it
# visually distinct from the stdlib uuid.UUID used in the annotations below.
from sqlalchemy.dialects.postgresql import UUID as PostgresUuid  # noqa: N811
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Root declarative base for all ACOP tables."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # SQLAlchemy 2.0 already uses RETURNING on INSERT, so server defaults are
    # populated after a create. It does *not* do so on UPDATE: a column with a
    # SQL-side ``onupdate`` (``updated_at``) is left expired, and the next read
    # of it needs a database round trip. Under asyncio that read happens inside
    # Pydantic's synchronous attribute extraction and raises MissingGreenlet,
    # so serialising any row that was just updated fails - which is every PATCH
    # and every retirement. Fetching eagerly adds a RETURNING clause to an
    # UPDATE already being issued. The alternative, moving ``onupdate`` to a
    # Python-side clock, would make ``created_at`` database time and
    # ``updated_at`` application time; once collectors run on several hosts
    # those two columns could no longer be ordered against each other.
    # RUF012 wants ClassVar here; SQLAlchemy declares ``__mapper_args__`` as an
    # instance variable on DeclarativeBase, so ClassVar is a mypy error. The
    # dict is never mutated, so the rule is suppressed rather than obeyed.
    __mapper_args__: dict[str, Any] = {"eager_defaults": True}  # noqa: RUF012


class UUIDPrimaryKeyMixin:
    """Adds a UUID primary key.

    UUIDs rather than sequential integers because assets, incidents and audit
    records will eventually be created by multiple collectors concurrently and
    referenced across systems. Generated application-side so that the value is
    known before the flush, which simplifies writing an audit record that
    references the object it describes.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PostgresUuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Adds creation and update timestamps, generated by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
