"""Alembic environment.

Runs migrations against the async engine so that development and production use
one driver. The database URL is read from ACOP's own settings, which means
migrations cannot drift from the application's connection configuration and no
credential is written into ``alembic.ini``.
"""

from __future__ import annotations

import asyncio
import re
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

import acop.models  # noqa: F401  # ensures all model modules are imported
from acop.config import get_settings

# Importing the models package registers every table on Base.metadata.
# Without this import, autogenerate produces an empty migration.
from acop.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

#: Embedding-space partitions are created at runtime by the space registration
#: service, not by a migration, because a space cannot be registered until its
#: provider's prompt-prefix behaviour has been verified - which a migration
#: cannot do. They are therefore absent from ``Base.metadata``, and without
#: this filter every ``alembic check`` after the first space is registered
#: would report them as tables to drop, permanently.
#:
#: Only child partitions are excluded. The partitioned *parent*
#: (``knowledge_embedding_d768``) is a normal model and is still compared, so
#: a change to its columns or constraints is caught as usual.
_PARTITION_NAME = re.compile(r"^knowledge_embedding_d\d+_.+$")


def _include_name(
    name: str | None, type_: str, parent_names: dict[str, str | None]
) -> bool:
    """Exclude runtime-created embedding partitions from autogenerate."""
    if type_ == "table" and name is not None and _PARTITION_NAME.match(name):
        return False
    return True


def _database_url() -> str:
    """Resolve the target database URL.

    A URL already set on the Config wins. That lets a caller - the integration
    test suite, or an operator running a migration against a restored copy -
    point Alembic somewhere specific without mutating the environment. When
    nothing is set, the URL comes from ACOP's own settings, so migrations can
    never drift from the application's connection configuration.
    """
    configured = config.get_main_option("sqlalchemy.url", None)
    if configured:
        return configured
    return get_settings().database_url


database_url = _database_url()
config.set_main_option("sqlalchemy.url", database_url)


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Detect column type changes; without this, an ALTER that only changes
        # a type is silently omitted from autogenerated migrations.
        compare_type=True,
        compare_server_default=True,
        # Required for the constraint naming convention on Base.metadata to be
        # applied to autogenerated batch operations.
        render_as_batch=False,
        include_name=_include_name,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting.

    Used to produce a reviewable SQL script for a change window.
    """
    context.configure(
        url=database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_name=_include_name,
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Apply migrations against a live database."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
